### ISSUE TITLE
Unable to create a Server w/ Existing DB on Heroku

### ISSUE THREAD

**Issue by hoodsy** [prismagraphql/prisma-cloud-feedback#197]
When attempting to create a new Server and connect it to an existing MySQL db, I encounter this error:

![screen shot 2018-08-03 at 11 44 27 am](https://user-images.githubusercontent.com/4467642/43720214-dcf5a362-995d-11e8-9245-7f9b9329eaa2.png)

@marktani

**Comment by kverpoorten** [comment]
I get the exact same error. It was a new account I just created half an hour before attempting to add a heroku server.
I also tried in another browser to make sure being logged in to a heroku account didn't cause it, but that didn't help.

**Comment by kverpoorten** [comment]
Hi, I discovered something that can probably help you figuring this out.

Creating a new server with an existing database kept failing, so I created a new server with a **new database**
That allowed me to link my prisma account to my heroku account

When I then later tried again creating a new server with an existing database, it **did work**

So it seems the problem lies with the authentication step when using an existing database. That would also explain why not everyone is having the issue.

Hope this helps you

**Comment by timsuchanek** [comment]
Thanks for the great reproduction information!
We just fixed this and the heroku auth screen now should correctly show when you connect you Heroku server with your own database.
Let me know if it's fixed for you now, if not we reopen the issue
